# Generated by Django 4.2.4 on 2023-09-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_healthtips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthtips',
            options={'verbose_name': 'Add Daily Tip'},
        ),
    ]
