# Generated by Django 4.2.4 on 2023-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_healthtips_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100, verbose_name='Country'),
        ),
    ]
