# Generated by Django 4.2.4 on 2023-09-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsinit',
            name='image',
            field=models.ImageField(default='default.png', upload_to='doctors', verbose_name='Add doctors Image'),
        ),
    ]
