# Generated by Django 4.2.4 on 2023-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctorsinit_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsqualifications',
            options={'verbose_name': 'Add Doctors Qualification'},
        ),
        migrations.AlterField(
            model_name='doctorsdays',
            name='days',
            field=models.CharField(choices=[(0, 'Monday - Friday'), (1, 'Saturday'), (2, 'Sunday')], max_length=20, verbose_name='Work Day'),
        ),
        migrations.AlterField(
            model_name='doctorsqualifications',
            name='skills',
            field=models.TextField(verbose_name='write About Skill'),
        ),
    ]
