# Generated by Django 4.2.4 on 2023-09-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_doctorsdays_days_alter_doctorstime_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsdays',
            options={'verbose_name': 'Work Day'},
        ),
        migrations.AlterModelOptions(
            name='doctorsinit',
            options={'verbose_name': 'Add Doctors Detail'},
        ),
        migrations.AlterModelOptions(
            name='doctorstime',
            options={'verbose_name': 'Work Time'},
        ),
        migrations.AlterModelOptions(
            name='doctorsworkhours',
            options={'verbose_name': 'set Doctors Work Time'},
        ),
    ]
