# Generated by Django 4.2.4 on 2023-09-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_doctorsdays_options_alter_doctorsinit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsdays',
            options={'verbose_name': 'Add Work Day'},
        ),
        migrations.AlterModelOptions(
            name='doctorstime',
            options={'verbose_name': 'Add Work Time'},
        ),
    ]
