# Generated by Django 4.2.4 on 2023-09-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_doctorsdays_options_alter_doctorstime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='doctors Department')),
                ('created_at', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Add Doctors Department',
            },
        ),
        migrations.CreateModel(
            name='DoctorsAndDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ManyToManyField(to='main.doctorsdepartment')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctorsinit')),
            ],
            options={
                'verbose_name': 'Merge Doctors Department',
            },
        ),
    ]
