# Generated by Django 4.2.4 on 2023-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_doctorsdepartment_doctorsanddepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subed_at', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'subscribed Users',
            },
        ),
    ]
