# Generated by Django 4.2.4 on 2023-09-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_subscription_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'subscribed User'},
        ),
    ]
