# Generated by Django 4.2.4 on 2023-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appiontments',
            name='phone',
        ),
        migrations.AddField(
            model_name='appiontments',
            name='contact',
            field=models.CharField(default='fndjnfjnjd', max_length=200, verbose_name='Contact'),
        ),
    ]
