# Generated by Django 4.2.4 on 2023-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_appiontments_phone_appiontments_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontments',
            name='contact',
            field=models.CharField(max_length=200, verbose_name='Contact'),
        ),
    ]
