# Generated by Django 4.2.4 on 2023-09-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_appiontments_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appiontments',
            options={'verbose_name': 'Appointment'},
        ),
    ]
