# Generated by Django 4.2.4 on 2023-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_appiontments_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontments',
            name='contact',
            field=models.EmailField(max_length=254, verbose_name='Contact'),
        ),
    ]
