# Generated by Django 4.2.4 on 2023-10-26 10:47

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_appiontments_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsdepartment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='department', editable=False, populate_from='department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='departmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.doctorsdepartment')),
            ],
        ),
    ]
