# Generated by Django 4.2.4 on 2023-10-26 10:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_doctorsdepartment_slug_departmentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdepartment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='department', editable=False, populate_from='department'),
        ),
    ]
