# Generated by Django 4.2.4 on 2023-10-26 10:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_doctorsdepartment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsdepartment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='department'),
        ),
    ]
