# Generated by Django 4.2.4 on 2023-10-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_doctorsdepartment_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentdetails',
            options={'verbose_name': 'Department Details'},
        ),
    ]
