# Generated by Django 4.2.4 on 2023-10-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_departmentdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentdetails',
            options={'verbose_name': 'Department Detail'},
        ),
    ]
