# Generated by Django 4.2.4 on 2023-10-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_departmentdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdetails',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.doctorsdepartment'),
        ),
    ]
