# Generated by Django 4.2.4 on 2023-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_departmentdetails_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="testifier's name")),
                ('service', models.CharField(max_length=50, verbose_name='subject')),
                ('testimoney', models.TextField(verbose_name='testimoney')),
            ],
            options={
                'verbose_name': 'Add Testimoney',
            },
        ),
    ]
