# Generated by Django 4.2.4 on 2023-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='sites')),
                ('site_number', models.IntegerField(verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(verbose_name='Face Book')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('linkedin', models.URLField(verbose_name='LikedIn')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('address', models.CharField(max_length=500, verbose_name='Hospital Address')),
                ('butter_combs', models.ImageField(upload_to='header_images')),
            ],
            options={
                'verbose_name': 'Site Socials',
            },
        ),
    ]
