# Generated by Django 4.2.4 on 2023-09-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedetails',
            options={'verbose_name': 'Site Social'},
        ),
    ]
