# Generated by Django 4.2.4 on 2023-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0002_alter_sitedetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_client', models.IntegerField(default=100, verbose_name='Happy Clients')),
                ('completed_surgery', models.IntegerField(default=100, verbose_name='Surgery Completed')),
                ('expert_doctors', models.IntegerField(default=100, verbose_name='Doctors')),
                ('branches', models.IntegerField(default=100, verbose_name='Branches')),
            ],
            options={
                'verbose_name': 'Website Counter',
            },
        ),
    ]
