# Generated by Django 4.2.4 on 2023-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0004_sitetestimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSayAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('work', models.CharField(max_length=100, verbose_name='Work')),
                ('message', models.TextField(max_length=50, verbose_name='Message')),
            ],
            options={
                'verbose_name': ' Add Words About Us',
            },
        ),
    ]
